upstream backend {
  server backend_server_1:3000;
  server backend_server_2:3001;
  server backend_server_3:3002;
}
server {
  listen 80;
  include /etc/nginx/mime.types;
  location / {
    proxy_pass http://backend/;
  }
}
